:recycle: Enable Buildkit as we use especial settings
Dockerfile has especial settings and we need buildkit

Sending build context to Docker daemon  167.4kB

Step 1/11 : FROM alpine AS dependencies
latest: Pulling from library/alpine
59bf1c3509f3: Already exists
Digest: sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
Status: Downloaded newer image for alpine:latest
 ---> c059bfaa849c
Step 2/11 : WORKDIR /google/trainings/haskell/cabal
 ---> Running in c3b031a1c863
Removing intermediate container c3b031a1c863
 ---> cbffd7feeb01
Step 3/11 : RUN --mount=type=bind,target=/docker-context     cd /docker-context/;     find . -type f \( -iname \*.cabal -o -iname \*.yaml\* \) -mindepth 0 -maxdepth 2          -exec cp --parents "{}" /google/trainings/haskell/cabal/ \;
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
Service '00_setup' failed to build : Build failed
Error: Process completed with exit code 1.